name: keynote_minimalist
description: Clean, focused presentation style inspired by Apple keynotes
version: 1.0.0

colors:
  background: "#000000"
  text_primary: "#FFFFFF"
  text_secondary: "rgba(255, 255, 255, 0.7)"
  accent: "#0A84FF"
  card_bg: "rgba(255, 255, 255, 0.05)"
  border: "rgba(255, 255, 255, 0.1)"

typography:
  primary_font: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Helvetica Neue', sans-serif"
  code_font: "'SF Mono', 'Consolas', 'Monaco', monospace"
  headline_size: "72px"
  headline_weight: 700
  body_size: "20px"
  body_weight: 400

layouts:
  - title_center
  - split_50_50
  - grid_thirds
  - stat_grid
  - code_example
  - cta_final

triggers:
  content_type:
    - feature_launch
    - vision
    - business
  audience:
    - executive
    - mixed
  technical_depth: 0.0-0.5
